#the inputs
a=input("enter a person noun:")
b=input("enter a adjective:")
c=input("enter a place noun:")
d=input("enter a hoppy:")
e=input("enter a time of day:") 
f=input("enter a feeling(1):") 
g=input("enter a string object noun:") 
h=input("enter a verbe:")
i=input("enter a animal noun:")
j=input("enter a adjective:")
k=input("enter a place noun:")
l=input("enter a weird action:")
m=input("enter a sound:")
n=input("enter a feeling(2):")
o=input("enter a name:")
p=input("enter a city name:")
q=input("enter a item noun:")
r=input("enter a adjective:")
s=input("enter a action:")
t=input("enter a expexted action:")
#the plane of madlibs game
print(" One day "+a+" was living a "+b+" life in a "+c+" spending most of their time enjoy "+d+" withot evryfeeling bored.")
print("In the "+e+",While feeling "+f+",He noticed a "+g+" nerby,Without thinking twice,He decided to "+h+" immediately,As if evrything was completely normal.")
print("Suddenly,A"+i+" that looked"+j+" appeared and sterted silently"+a+" foolowed  the "+i+" Until they reached a "+k+".")
print("Wher somthing totally unexpected happened.Evryone started "+l+" and the sound of "+m+" echoed evrywhere.")
print(a+" felt "+n+" and could not decide whether to laught or run away at that moment.")
print(a+" remembered their friend "+o+"when said:\"if you ever reach"+p+"be careful not to lose your"+q+"\"")
print("But it was too late,Evrything became"+r+",So "+a+" had to"+s+" to save situation.")
print("In the end,"+t+" and no one ever knew whether it was a real adventure or judt a very strange dream.")
print("The end.")
print("thank you for playing\nThis game made by:Abdali Tayeb Larabi\nThis story made by:yara ezzianl")